### ISSUE TITLE
Load as System in the browser

### ISSUE THREAD

**Issue by sebdeckers** [ModuleLoader/system-register-loader#4]
Thanks for creating this loader. 🙇 

I have an aesthetic question: Would it make sense to automatically declare an instance as the global `System` variable in the browser?

That way it's a drop-in replacement for the full-size `system.js` library. A user could follow the usual SystemJS entry snippet:

``` html
<script src="dist/system-register-loader.js"></script>
<script>
  System.import('./path/to/file.js').then(function(m) {
    // ...
  });
</script>
```

**Comment by probins** [comment]
I'm not sure that `System` is still planned as a global. The direction in TC39 seems to be the other way, e.g. it looks like `System.global` will now be just `global`. The [current proposal](https://github.com/domenic/proposal-dynamic-import) is to have `import()`, not `System.import()`. Personally, I am continuing to create and use `System` for the moment (apart from anything else, I don't know how you polyfill `import()`), but at some point I will have to change this.

**Comment by sebdeckers** [comment]
TIL :dizzy: Thanks!
