### ISSUE TITLE
Add docs and example for `nomodule`

### ISSUE THREAD

**Issue by probins** [ModuleLoader/system-register-loader#6]
As there seems to be general agreement on a `nomodule` attribute for `<script>` https://github.com/whatwg/html/pull/2261, I'd suggest adding an example which uses native ES loader if supported, with a `nomodule` script loading the polyfill with System.register modules if not. This scenario could also usefully be documented both in this repo and in the main es-module-loader one.

Should I put together a PR?

**Comment by guybedford** [comment]
I'm not going to advocate a workflow that isn't yet proven to be useful.
